import {
  Activity,
  Apple,
  Armchair,
  Bed,
  Book,
  Building,
  Car,
  Cat,
  Gift,
  Heart,
  House,
  Landmark,
  MonitorSmartphone,
  MountainSnow,
  Package,
  Paintbrush,
  PhoneCall,
  Shirt,
  Shrub,
  Unplug,
  Volleyball,
  WashingMachine,
} from "lucide-react";

export const mapIcons = {
  activity: Activity,
  building: Building,
  gift: Gift,
  cat: Cat,
  book: Book,
  phoneCall: PhoneCall,
  monitorSmartphone: MonitorSmartphone,
  paintbrush: Paintbrush,
  package: Package,
  unplug: Unplug,
  heart: Heart,
  landmark: Landmark,
  apple: Apple,
  armchair: Armchair,
  bed: Bed,
  mountainSnow: MountainSnow,
  shrub: Shrub,
  volleyball: Volleyball,
  shirt: Shirt,
  washingMachine: WashingMachine,
  car: Car,
  house: House,
};
