name: Frontend CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: aTrueYety/idatt2106-2025-09-backend
          ref: dev
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install maven -y
      - name: Build with Maven
        run: mvn -B package -Dspring.profiles.active=test-e2e -Ptest-e2e
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: target/

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    env:
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXT_PUBLIC_API_URL: localhost:8080
      NEXT_PUBLIC_USE_HTTPS: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build Next.js
        run: npm run build
      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: .next
          include-hidden-files: true

  e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    env:
      # Backend in-memory H2
      DATABASE_URL: jdbc:h2:mem:testdb;Mode=MySQL
      DATABASE_USER: h2
      DATABASE_PASSWORD: h2
      SPRING_DATABASE_DRIVER: org.h2.Driver

      # NextAuth & front-end
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXT_PUBLIC_API_URL: localhost:8080
      NEXT_PUBLIC_USE_HTTPS: false
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      DATABASE_SCHEMA: default

    steps:
      # Get your front-end code (package.json, public/, etc.)
      - name: Checkout Frontend Code
        uses: actions/checkout@v4

      # Install next + deps so `next start` works
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci

      # Bring in your pre-built .next folder
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: .next/

      # Start Next.js in prod mode
      - name: Start Frontend
        run: |
          nohup npm run start &   # or `npx next start`
          sleep 5

      # Now prepare & start your backend
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: backend/
      - name: Start Backend
        run: |
          nohup java -jar backend/backend-0.0.1-SNAPSHOT.jar --spring.profiles.active=test-e2e &
          sleep 20

      # Run your Cypress suite
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6

      # Persist screenshots on failure
      - name: Upload Cypress Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: cypress/screenshots
